grocery_list:
  path: /offer/list
  controller: App\Controller\GroceryList\GroceryOfferListController::offerList

grocery_list_sort:
  path: /list
  controller: App\Controller\GroceryList\GroceryOfferListController::sortItems
  methods: GET